services:
  service.validation:
    class: CustomValidationBundle\Service\ValidationService
    arguments:
      - '@validator'
    public: false

  CustomValidationBundle\Service\ValidationServiceInterface:
    alias: service.validation
    public: true
