services:
  service.validation:
    class: ViachViach\CustomValidationBundle\Service\ValidationService
    arguments:
      - '@validator'
    public: false

  ViachViach\CustomValidationBundle\Service\ValidationServiceInterface:
    alias: service.validation
    public: true
